// This file is auto-generated by @hey-api/openapi-ts

export const SpecificationSchema = {
    type: 'object',
    properties: {
        api_key_id: {
            type: ['string', 'null'],
            format: 'uuid',
            example: 'e4ce4324-1177-47ca-aeef-b1d011bd3932'
        },
        actor: {
            type: ['string', 'null'],
            example: 'mrlubos'
        },
        actor_id: {
            type: ['string', 'null'],
            example: '12529395'
        },
        branch: {
            type: ['string', 'null'],
            example: 'feat/awesome-feature'
        },
        branch_base: {
            type: ['string', 'null'],
            example: 'main'
        },
        ci_platform: {
            type: ['string', 'null'],
            example: 'github'
        },
        commit_sha: {
            type: ['string', 'null'],
            example: '1c6945d83eab3580791eb4148562b3bd2e16df14'
        },
        creator_user_id: {
            type: ['string', 'null'],
            format: 'uuid',
            example: '5d2827a4-b3fc-4946-bb3b-72f23e89c6aa'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        },
        event_name: {
            type: ['string', 'null'],
            example: 'push'
        },
        id: {
            type: 'string',
            format: 'uuid',
            example: 'e4ce4324-1177-47ca-aeef-b1d011bd3932'
        },
        job: {
            type: ['string', 'null'],
            example: 'ci'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            example: 'e4ce4324-1177-47ca-aeef-b1d011bd3932'
        },
        ref: {
            type: ['string', 'null'],
            example: 'refs/heads/main'
        },
        ref_type: {
            type: ['string', 'null'],
            example: 'branch'
        },
        repository: {
            type: ['string', 'null'],
            example: 'hey-api/platform'
        },
        run_id: {
            type: ['string', 'null'],
            example: '13448896305'
        },
        run_number: {
            type: ['string', 'null'],
            example: '1'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        },
        tags: {
            type: 'array',
            items: {
                type: 'string'
            },
            example: ['dev']
        },
        version: {
            type: ['string', 'null'],
            example: '1.0.0'
        },
        workflow: {
            type: ['string', 'null'],
            example: 'CI'
        }
    },
    required: ['api_key_id', 'actor', 'actor_id', 'branch', 'branch_base', 'ci_platform', 'commit_sha', 'creator_user_id', 'created_at', 'event_name', 'id', 'job', 'project_id', 'ref', 'ref_type', 'repository', 'run_id', 'run_number', 'updated_at', 'tags', 'version', 'workflow']
} as const;

export const CursorResponseSchema = {
    type: 'object',
    properties: {
        end_cursor: {
            type: ['string', 'null'],
            format: 'uuid',
            example: 'e4ce4324-1177-47ca-aeef-b1d011bd3932'
        },
        has_next_page: {
            type: ['boolean', 'null'],
            example: true
        },
        has_previous_page: {
            type: ['boolean', 'null'],
            example: true
        },
        start_cursor: {
            type: ['string', 'null'],
            format: 'uuid',
            example: 'e4ce4324-1177-47ca-aeef-b1d011bd3932'
        }
    },
    required: ['end_cursor', 'has_next_page', 'has_previous_page', 'start_cursor']
} as const;

export const OrganizationSchema = {
    type: 'object',
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        },
        creator_user_id: {
            type: ['string', 'null'],
            format: 'uuid',
            example: '5d2827a4-b3fc-4946-bb3b-72f23e89c6aa'
        },
        id: {
            type: 'string',
            format: 'uuid',
            example: 'e4ce4324-1177-47ca-aeef-b1d011bd3932'
        },
        name: {
            type: 'string',
            example: 'Hey API'
        },
        slug: {
            type: 'string',
            example: 'hey-api'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        }
    },
    required: ['created_at', 'creator_user_id', 'id', 'name', 'slug', 'updated_at']
} as const;

export const RoleSchema = {
    type: 'object',
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        },
        id: {
            type: 'string',
            format: 'uuid',
            example: 'e4ce4324-1177-47ca-aeef-b1d011bd3932'
        },
        organization_id: {
            type: 'string',
            format: 'uuid',
            example: 'e4ce4324-1177-47ca-aeef-b1d011bd3932'
        },
        status: {
            type: 'string',
            enum: ['active', 'invited', 'suspended'],
            example: 'active'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            example: '5d2827a4-b3fc-4946-bb3b-72f23e89c6aa'
        }
    },
    required: ['created_at', 'id', 'organization_id', 'status', 'updated_at', 'user_id']
} as const;

export const UserSchema = {
    type: 'object',
    properties: {
        clerk_user_id: {
            type: ['string', 'null'],
            example: 'user_2tDpMYgevIkZOL76Wo6VzXxsbxD'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        },
        email: {
            type: ['string', 'null'],
            example: 'lubos@heyapi.dev'
        },
        first_name: {
            type: ['string', 'null'],
            example: 'Lubos'
        },
        id: {
            type: 'string',
            format: 'uuid',
            example: 'e4ce4324-1177-47ca-aeef-b1d011bd3932'
        },
        image_url: {
            type: ['string', 'null'],
            example: 'https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2ltYWdlcy5jbGVyay5kZXYvdXBsb2FkZWQvaW1nXzJ0RzFucjNDbzg2azhDTWNoUlBxTHViVEdtTiJ9'
        },
        last_name: {
            type: ['string', 'null'],
            example: 'Menus'
        },
        roles: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Role'
            }
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        }
    },
    required: ['clerk_user_id', 'created_at', 'email', 'first_name', 'id', 'image_url', 'last_name', 'updated_at']
} as const;

export const ProjectSchema = {
    type: 'object',
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        },
        creator_user_id: {
            type: ['string', 'null'],
            format: 'uuid',
            example: '5d2827a4-b3fc-4946-bb3b-72f23e89c6aa'
        },
        default_branch: {
            type: ['string', 'null'],
            example: 'main'
        },
        id: {
            type: 'string',
            format: 'uuid',
            example: 'e4ce4324-1177-47ca-aeef-b1d011bd3932'
        },
        name: {
            type: 'string',
            example: 'Backend'
        },
        organization_id: {
            type: 'string',
            format: 'uuid',
            example: 'e4ce4324-1177-47ca-aeef-b1d011bd3932'
        },
        slug: {
            type: 'string',
            example: 'backend'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        }
    },
    required: ['created_at', 'creator_user_id', 'default_branch', 'id', 'name', 'organization_id', 'slug', 'updated_at']
} as const;

export const ApiKeyConcealedSchema = {
    type: 'object',
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        },
        creator_user_id: {
            type: ['string', 'null'],
            format: 'uuid',
            example: '5d2827a4-b3fc-4946-bb3b-72f23e89c6aa'
        },
        id: {
            type: 'string',
            format: 'uuid',
            example: 'e4ce4324-1177-47ca-aeef-b1d011bd3932'
        },
        last_used_at: {
            type: ['string', 'null'],
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        }
    },
    required: ['created_at', 'creator_user_id', 'id', 'last_used_at', 'updated_at']
} as const;

export const ApiKeySchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/ApiKeyConcealed'
        },
        {
            type: 'object',
            properties: {
                value: {
                    type: 'string',
                    example: 'xx_xxxx_xxxx_xxxxxxxxxxxxxxxxxxxxxxxx'
                }
            },
            required: ['value']
        }
    ]
} as const;

export const WebhookConcealedSchema = {
    type: 'object',
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        },
        creator_user_id: {
            type: ['string', 'null'],
            format: 'uuid',
            example: '5d2827a4-b3fc-4946-bb3b-72f23e89c6aa'
        },
        endpoint: {
            type: 'string',
            example: 'https://example.com/api/webhooks'
        },
        id: {
            type: 'string',
            format: 'uuid',
            example: 'e4ce4324-1177-47ca-aeef-b1d011bd3932'
        },
        is_enabled: {
            type: 'boolean',
            example: true
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            example: 'e4ce4324-1177-47ca-aeef-b1d011bd3932'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        }
    },
    required: ['created_at', 'creator_user_id', 'endpoint', 'id', 'is_enabled', 'project_id', 'updated_at']
} as const;

export const WebhookSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/WebhookConcealed'
        },
        {
            type: 'object',
            properties: {
                secret: {
                    type: 'string',
                    example: 'whsec_666a85c7f7ce8c891be0f650b21d0749'
                }
            },
            required: ['secret']
        }
    ]
} as const;

export const WaitlistFeatureSchema = {
    type: 'string',
    enum: ['analytics', 'changelogs', 'integrations', 'mcp', 'mocks', 'sdks', 'tests'],
    example: 'sdks'
} as const;

export const WaitlistSchema = {
    type: 'object',
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        },
        feature: {
            '$ref': '#/components/schemas/WaitlistFeature'
        },
        id: {
            type: 'string',
            format: 'uuid',
            example: 'e4ce4324-1177-47ca-aeef-b1d011bd3932'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            example: '2025-02-21T02:37:15.840Z'
        }
    },
    required: ['created_at', 'feature', 'id', 'updated_at']
} as const;