// This file is auto-generated by @hey-api/openapi-ts

export type BodyLogin = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserPublic = {
    uuid?: string;
    user_id: string;
    is_active?: boolean;
    id: number;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ApiStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/usuarios/status';
};

export type ApiStatusResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginData = {
    body: BodyLogin;
    path?: never;
    query?: never;
    url: '/api/usuarios/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type TestAccessTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/usuarios/test-token';
};

export type TestAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type TestAccessTokenResponse = TestAccessTokenResponses[keyof TestAccessTokenResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/usuarios/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};