/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as JuegosIndexImport } from './routes/juegos/index'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutLeaderboardImport } from './routes/_layout/leaderboard'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as JuegosPokemonIndexImport } from './routes/juegos/pokemon/index'
import { Route as JuegosAjedrezIndexImport } from './routes/juegos/ajedrez/index'
import { Route as JuegosPokemonLeaderboardImport } from './routes/juegos/pokemon/leaderboard'
import { Route as JuegosAjedrezLeaderboardImport } from './routes/juegos/ajedrez/leaderboard'
import { Route as JuegosPokemonComponentsPokemonListComponentImport } from './routes/juegos/pokemon/components/PokemonListComponent'
import { Route as JuegosPokemonComponentsFindingMatchComponentImport } from './routes/juegos/pokemon/components/FindingMatchComponent'
import { Route as JuegosPokemonComponentsBattleComponentImport } from './routes/juegos/pokemon/components/BattleComponent'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const JuegosIndexRoute = JuegosIndexImport.update({
  path: '/juegos/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLeaderboardRoute = LayoutLeaderboardImport.update({
  path: '/leaderboard',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const JuegosPokemonIndexRoute = JuegosPokemonIndexImport.update({
  path: '/juegos/pokemon/',
  getParentRoute: () => rootRoute,
} as any)

const JuegosAjedrezIndexRoute = JuegosAjedrezIndexImport.update({
  path: '/juegos/ajedrez/',
  getParentRoute: () => rootRoute,
} as any)

const JuegosPokemonLeaderboardRoute = JuegosPokemonLeaderboardImport.update({
  path: '/juegos/pokemon/leaderboard',
  getParentRoute: () => rootRoute,
} as any)

const JuegosAjedrezLeaderboardRoute = JuegosAjedrezLeaderboardImport.update({
  path: '/juegos/ajedrez/leaderboard',
  getParentRoute: () => rootRoute,
} as any)

const JuegosPokemonComponentsPokemonListComponentRoute =
  JuegosPokemonComponentsPokemonListComponentImport.update({
    path: '/juegos/pokemon/components/PokemonListComponent',
    getParentRoute: () => rootRoute,
  } as any)

const JuegosPokemonComponentsFindingMatchComponentRoute =
  JuegosPokemonComponentsFindingMatchComponentImport.update({
    path: '/juegos/pokemon/components/FindingMatchComponent',
    getParentRoute: () => rootRoute,
  } as any)

const JuegosPokemonComponentsBattleComponentRoute =
  JuegosPokemonComponentsBattleComponentImport.update({
    path: '/juegos/pokemon/components/BattleComponent',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/leaderboard': {
      preLoaderRoute: typeof LayoutLeaderboardImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/juegos/': {
      preLoaderRoute: typeof JuegosIndexImport
      parentRoute: typeof rootRoute
    }
    '/juegos/ajedrez/leaderboard': {
      preLoaderRoute: typeof JuegosAjedrezLeaderboardImport
      parentRoute: typeof rootRoute
    }
    '/juegos/pokemon/leaderboard': {
      preLoaderRoute: typeof JuegosPokemonLeaderboardImport
      parentRoute: typeof rootRoute
    }
    '/juegos/ajedrez/': {
      preLoaderRoute: typeof JuegosAjedrezIndexImport
      parentRoute: typeof rootRoute
    }
    '/juegos/pokemon/': {
      preLoaderRoute: typeof JuegosPokemonIndexImport
      parentRoute: typeof rootRoute
    }
    '/juegos/pokemon/components/BattleComponent': {
      preLoaderRoute: typeof JuegosPokemonComponentsBattleComponentImport
      parentRoute: typeof rootRoute
    }
    '/juegos/pokemon/components/FindingMatchComponent': {
      preLoaderRoute: typeof JuegosPokemonComponentsFindingMatchComponentImport
      parentRoute: typeof rootRoute
    }
    '/juegos/pokemon/components/PokemonListComponent': {
      preLoaderRoute: typeof JuegosPokemonComponentsPokemonListComponentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutLeaderboardRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
  ]),
  LoginRoute,
  JuegosIndexRoute,
  JuegosAjedrezLeaderboardRoute,
  JuegosPokemonLeaderboardRoute,
  JuegosAjedrezIndexRoute,
  JuegosPokemonIndexRoute,
  JuegosPokemonComponentsBattleComponentRoute,
  JuegosPokemonComponentsFindingMatchComponentRoute,
  JuegosPokemonComponentsPokemonListComponentRoute,
])

/* prettier-ignore-end */
