FROM nginx:1

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./index.html /usr/share/nginx/html
COPY ./script.js /usr/share/nginx/html/
COPY ./style.css /usr/share/nginx/html/

COPY ./script.js /usr/share/nginx/html/juegos/conecta4/
COPY ./style.css /usr/share/nginx/html/juegos/conecta4/
